// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmjQ1GRix7rgm755z0tVzheGWxUP6T-_A',
    appId: '1:213133341906:web:6a0647659eb6f4ee77690b',
    messagingSenderId: '213133341906',
    projectId: 'fitfolio-38aec',
    authDomain: 'fitfolio-38aec.firebaseapp.com',
    storageBucket: 'fitfolio-38aec.appspot.com',
    measurementId: 'G-J64WHGLBFY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwZuhh8MtLalSXBW5gPV6PO2l696TjcqY',
    appId: '1:213133341906:android:7746810fb254131277690b',
    messagingSenderId: '213133341906',
    projectId: 'fitfolio-38aec',
    storageBucket: 'fitfolio-38aec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxpXk_dlerT36yvMPuUJxPCVf_vpXP6H4',
    appId: '1:213133341906:ios:f73031b4c00ce4f777690b',
    messagingSenderId: '213133341906',
    projectId: 'fitfolio-38aec',
    storageBucket: 'fitfolio-38aec.appspot.com',
    iosClientId: '213133341906-3251bq7ka88cllbrbnp6toan30o21rr0.apps.googleusercontent.com',
    iosBundleId: 'com.fitfolio.fitfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxpXk_dlerT36yvMPuUJxPCVf_vpXP6H4',
    appId: '1:213133341906:ios:3da3cef079a52c9677690b',
    messagingSenderId: '213133341906',
    projectId: 'fitfolio-38aec',
    storageBucket: 'fitfolio-38aec.appspot.com',
    iosClientId: '213133341906-gtm1kn52s30335drdd2ke81rruhh3mae.apps.googleusercontent.com',
    iosBundleId: 'com.fitfolio.fitfolio.RunnerTests',
  );
}
